# A wrapper template around the common .NET build-test-publish-repo template with settings
# specific to the Dockerfiles in this repo.

parameters:
  noCache: false
  internalProjectName: null
  publicProjectName: null

stages:
- template: ../../common/templates/stages/dotnet/build-test-publish-repo.yml
  parameters:
    noCache: ${{ parameters.noCache }}
    internalProjectName: ${{ parameters.internalProjectName }}
    publicProjectName: ${{ parameters.publicProjectName }}
    ${{ if eq(variables['System.TeamProject'], parameters.publicProjectName) }}:
      buildMatrixType: platformVersionedOs
      buildMatrixCustomBuildLegGroupArgs: --custom-build-leg-group pr-build --custom-build-leg-group test-dependencies
    ${{ if eq(variables['System.TeamProject'], parameters.internalProjectName) }}:
      buildMatrixCustomBuildLegGroupArgs: --custom-build-leg-group test-dependencies
    testMatrixCustomBuildLegGroupArgs: --custom-build-leg-group test-dependencies

    # Template paths must be relative to the YAML job that executes them
    customBuildInitSteps:
    - template: ../../../pipelines/steps/set-imagebuilder-build-args-var.yml
    - template: ../../../pipelines/steps/set-public-source-branch-var.yml
    - powershell: |
        $imageBuilderBuildArgs = ""
        if ("$(publishRepoPrefix)".Contains("/internal/")) {
          if ("$(enableInternal3.1)" -eq "true") {
            $sasQueryString = "$(dotnetclimsrc-sas-query-string)"
          }
          else {
            $sasQueryString = "$(dotnetbuilds-internal-container-read-token)"
          }
          
          $imageBuilderBuildArgs = "--build-arg SAS_QUERY_STRING='$(dotnetclimsrc-sas-query-string)'"
        }
        echo "##vso[task.setvariable variable=imageBuilderBuildArgs]$imageBuilderBuildArgs"
      displayName: Set Custom Build Variables
    customTestInitSteps:
    - powershell: |
        $testRunnerOptions=""
        $testInit=""

        if ("$(publishRepoPrefix)".Contains("/internal/")) {
          if ("$(enableInternal3.1)" -eq "true") {
            $sasQueryString = "$(dotnetclimsrc-sas-query-string)"
          }
          else {
            $sasQueryString = "$(dotnetbuilds-internal-container-read-token)"
          }

          if ($Env:AGENT_OS -eq 'Linux') {
            $testRunnerOptions=echo $('-e SAS_QUERY_STRING="$sasQueryString" -e NUGET_FEED_PASSWORD="$(dn-bot-dnceng-artifact-feeds-rw)"')
          }

          if ($Env:AGENT_OS -eq 'Windows_NT') {
              $testInit='$Env:SAS_QUERY_STRING=''$sasQueryString''; $Env:NUGET_FEED_PASSWORD=''$(dn-bot-dnceng-artifact-feeds-rw)'''
          }
        }
        
        echo "##vso[task.setvariable variable=testRunner.options]$testRunnerOptions"
        echo "##vso[task.setvariable variable=test.init]$testInit"
      displayName: Set Custom Test Variables
    customPublishInitSteps:
    - template: ../../../pipelines/steps/set-public-source-branch-var.yml
    - template: ../../../pipelines/steps/set-publish-mcrdocs-args-var.yml
