parameters:
  buildMatrixType: platformDependencyGraph
  noCache: false
  internalProjectName: null
  publicProjectName: null
  
  isInternalServicingValidation: false
  customGenerateMatrixInitSteps: []
  buildMatrixCustomBuildLegGroupArgs: ""
  testMatrixCustomBuildLegGroupArgs: ""
  customCopyBaseImagesInitSteps: []
  customBuildInitSteps: []
  customTestInitSteps: []
  customPublishInitSteps: []
  windowsAmdBuildJobTimeout: 60
  windowsAmdTestJobTimeout: 60
  linuxAmdBuildJobTimeout: 60
  linuxArmBuildJobTimeout: 60
  linuxAmd64Pool: ""
  
  testMatrixType: platformVersionedOs

stages:
- template: /eng/common/templates/stages/dotnet/build-and-test.yml
  parameters:
    buildMatrixType: ${{ parameters.buildMatrixType }}
    noCache: ${{ parameters.noCache }}
    internalProjectName: ${{ parameters.internalProjectName }}
    publicProjectName: ${{ parameters.publicProjectName }}
    isInternalServicingValidation: ${{ parameters.isInternalServicingValidation }}
    customGenerateMatrixInitSteps: ${{ parameters.customGenerateMatrixInitSteps }}
    buildMatrixCustomBuildLegGroupArgs: ${{ parameters.buildMatrixCustomBuildLegGroupArgs }}
    testMatrixCustomBuildLegGroupArgs: ${{ parameters.testMatrixCustomBuildLegGroupArgs }}
    customCopyBaseImagesInitSteps: ${{ parameters.customCopyBaseImagesInitSteps }}
    customBuildInitSteps: ${{ parameters.customBuildInitSteps }}
    customTestInitSteps: ${{ parameters.customTestInitSteps }}
    windowsAmdBuildJobTimeout: ${{ parameters.windowsAmdBuildJobTimeout }}
    windowsAmdTestJobTimeout: ${{ parameters.windowsAmdTestJobTimeout }}
    linuxAmdBuildJobTimeout: ${{ parameters.linuxAmdBuildJobTimeout }}
    linuxArmBuildJobTimeout: ${{ parameters.linuxArmBuildJobTimeout }}
    linuxAmd64Pool: ${{ parameters.linuxAmd64Pool }}
    testMatrixType: ${{ parameters.testMatrixType }}
- template: /eng/common/templates/stages/dotnet/publish.yml
  parameters:
    internalProjectName: ${{ parameters.internalProjectName }}
    publicProjectName: ${{ parameters.publicProjectName }}
    isInternalServicingValidation: ${{ parameters.isInternalServicingValidation }}
    customPublishInitSteps: ${{ parameters.customPublishInitSteps }}
